language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO_VERSION=2.3
  - DJANGO_VERSION=3.1
services:
  - postgresql
install: pip install psycopg2-binary PyYAML "Django<$DJANGO_VERSION"
before_script:
  - psql -U postgres -c 'create database django_postgres_utils;'
  - cd $TRAVIS_BUILD_DIR/src/
script: POSTGRES_USER="postgres" POSTGRES_PASSWORD="" ./manage.py test
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "ngP821I6cjidP1n+RmUb/f5dySDOk+vyeE2+LYgI1HeTAwlFkQevua6iyYZ2faozI4hdzGIeRiLMhHQGeOBXGpkKKT/MoYsXwgHJicqD7HI+VhF1XSIYaZ4A+zatEI5Q7n6nTfjx8KrvoYIJCPkWltdVHKkWlR63xYqang9/Sm7VJJHFg+F8tYVEwS37WOvARbE0yFVXgpL0qvV/xSqZHnGYxzXVgM8vpxlQLxl2m7/qnvD/bt9Z9prC7joPCWNk9zcbb+wb+zd+/fTQuGSNUH5J8lUk9H2jQrmbPchrlrjqTDUkpyboKpIfE5iVsFmgcoxRgWtkIVB5rUSZsfb4R9GjRVBQexIMdE7fPq9qBFtUOtOv1TF5WitWLq1hxMxgCZ8Y8YRuY+m64oAwDfPtFfCnmpqgkRwt+9sOwZmKgFNU45u2deg3/F2zqwmjC2wwwZ/ZPUbLN5h/I6/HRYnXemMNz6Z6SfmVmZfdNsE8SN58pahEgjM4QDl45IYDhzNTsHeu5ZL1VasXaDxeNshCxb3IwJ8o455+Zd7xk6mZTaSQqQY7wqMEpBgJA/vn6/cNej0nleO7UWG8ZOqU/ks/83KY7CEi6DVRg0nCiNWKlc4nz/upO5yaUgqi3XcdWDlJHoMpOMR+7F4+ZDn8Aw2DB+xvG8Uyk9fOwg/hbErrIRI="
  on:
    tags: true
    branch: master
  skip_existing: true
  skip_cleanup: true