language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO_VERSION=2.3
  - DJANGO_VERSION=3.1
services:
  - postgresql
install: pip install psycopg2-binary PyYAML "Django<$DJANGO_VERSION"
before_script:
  - psql -U postgres -c 'create database django_postgres_utils;'
  - cd $TRAVIS_BUILD_DIR/src/
script: POSTGRES_USER="postgres" POSTGRES_PASSWORD="" ./manage.py test
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "ODtSsOEKsP0Dexo1+IUn7+6fVtseaPy1U0e2jPOeeaP88oXFcdSGR03SfzHfM2PSixX8+tGu0rzNUr8VTIolebDYbH9XXlBVLbOez/MJrZk8rJS5Tku2PrqJ/mVpR4S6/rspXqDetboMQM3t8BTAuOTahkEDBejJ9FewBcyXs8kTuckJ+FEcPN3qdDYIGB3RLLZv5sGUYhZJXfn/3wYUV3tK9Vt+gOa30+Swvni2+2K1suGNPPnm8DmEIfz1Rdn6vDG8d6omrTn2dqWPXzzAFBIekOFyzON7EoCkVZS1Nm6LmrM6zM7SeMTeZ9StGB4Xw3v/YrucDaHSQ8J662qqPWsAUk0PgJvDYcq7dF6bnYUinmDFoJT11fDXa0BGn92KFTwpMx+CM2aPp4CMtJli+PVZitP0oGTlTT0zTe00Jvq80ts2G21skzPtb7d5KwDBaVPXq9avd0OLngZEXiu/LbWlvoZFc3+T5hJ9Aj3EbqMBQgdEYcg0dchwCEPc9ZVutcTte+gYTbBb8f5MPPEEb+znZzCOw1uc8oPq1lEEuTKPf9flXsc1fn2vZ5y2lw1BwjC8zP2Bt78dCbP6v6IK5XydMJxqctX8RnbFymkF3GVH904c2ureh5qDMK7C0RDZbmiiKUsGoxCOlREVkwiTAOyyU/moZWUIatv5kfWfRLk="
  on:
    all_branches: true
  skip_existing: true
  skip_cleanup: true