language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO_VERSION=2.3
  - DJANGO_VERSION=3.1
services:
  - postgresql
install: pip install psycopg2-binary PyYAML "Django<$DJANGO_VERSION"
before_script:
  - psql -U postgres -c 'create database django_postgres_utils;'
  - cd $TRAVIS_BUILD_DIR/src/
script: POSTGRES_USER="postgres" POSTGRES_PASSWORD="" ./manage.py test
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "JAQ50LgqGq/++T8xiBJP8dW92WfGu9ik/o0qqULB4JvX+CgJh9bYV6ZeuneZwdtT35tmTSHFrRuat4RT7ehI7Usl0nVZmhtJzj8e5xXlQbBxp1ZdBxQu680a+5OpDINiyf84p8W6crmHAjRPG9TCiBuW9xTHGKGDMvO/74IKRRSUDCWmt4IAXT8JJJCHgwtKx0YEk48a6CS26KuKRIloG7hDYidTB9hwTNvLDbkB7tz3WF2F2p778DX3EAG4KF8Sp1xmE3CCz6NkPl1+uRy/3ufeKK1VPBvNn0Z3jGoBK0K/Y4oJoQnFaT1U+b7K/VnNKSWwtcxjWUXm9/G56HFzpGGdoap5NO9SYK+W4OIm+tpoSAy7pxuvn5+c9jS1EEBF3vJJoe8dG/dgCpkQdDxmw2H+QbV6l/Qy6PKWEbvogxPfEmQrSbzAEumNRhAtzSDOu5gPDSfJxaK7oDr45aE5zjx5O9Kr7f3lytMoce3ew8deUcJvntXr8QTpUKuIvKVREJfurXbAEchjGFlxfU90eS9cxCVt18KbWwNoi4Lp9QuTCfHeBDFA3mAh4cIf6b+lIz0gbFU/a4KJ4f6zyJ1hYQKi3ii2ZhMA33NGNwN3fOkJc0xgaKVPyUkvgkeKw014HF9NwHWWsCbYcjDUOspc3NJXB3Ykeg/YygTN8BDAYlk="
  on:
    all_branches: true
  skip_existing: true
  skip_cleanup: true