language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO_VERSION=2.3
  - DJANGO_VERSION=3.1
services:
  - postgresql
install: pip install psycopg2-binary PyYAML "Django<$DJANGO_VERSION"
before_script:
  - psql -U postgres -c 'create database django_postgres_utils;'
  - cd $TRAVIS_BUILD_DIR/src/
script: POSTGRES_USER="postgres" POSTGRES_PASSWORD="" ./manage.py test
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure:  "j4IiyYneXMOYiUTxhiO45oH5JVVoiVwiJz2lZ8ZzdKXEun4HgQZATAH2on6HWs7uepj1zKLNj1mShE9ABBvu0sijA3ffRlEnp6tWg4iGSF0sD+Ik281G/1KwE2gFIrwzWVYiMIJqKWPl8P3p8HgzRE1ktyiSVoy7yO+iBUmZwRpGNH3kH+Ic5gg6G0lP2XNM5vY99MJ4DuwtDN39/akn0Qutw8wlxWDh74j/NI8AyGPaQW49iAyuP8d5bQ3BIIIxvvsZ0nnSTCeaY/q6fMtlcdKHVagsP+zaYjjWhPuxv63FovMJ19UUf2eHS8y0lraij46Qmujt2uVcZX80bXnwlfUI3nDlMkyTxf9rmhDt4b1h8qz16gFo7kfnDSXzQ3D9fThh2HnxUe5GISlYyQxBKaBWkNps3YaP5m+E6AK6ThbQawMbriv4wnXruDYm8sTydwvlTpuMjnPFy15APqX0D8fhbMUr1dl7FN99vaHE1P4hxHbmxuUT+XEsQlBZzuykE41+EUB3V8Bga2Zad0Dvea1M3mS6S0jbSYws/CQyWZL/N/eZ5GwElyAC9VU6IRNZEQANp6lT/TLxmDDXdccvPhRVv4rMiW4eK9bOYwvpvkRwBcQEoc+jVrrA15b5SeQiaMFqbvuiwH7psSTIrkzij15s02SyZO5vdStMZVPai6Q="
  on:
    tags: true
    branch: master
  skip_existing: true
  skip_cleanup: true